import React, { Component, useRef, useEffect } from "react";
import Head from "next/head";
import { CiTwitter, CiLinkedin } from "react-icons/ci";
import { AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import logo from "../public/BB.png";
import Home from "./home";
import Resume from "./resume";
import About from "./about";
import dynamic from "next/dynamic";
import enUS from "../locales/en-US.json";

export default function Index() {
  const TechStack = dynamic(() => import("./techstack"), { ssr: false });

  const nextSection2 = (id) => {
    console.log("nextsection2");
    console.log(id);
    var ref = document.getElementById(id);
    setTimeout(function () {
      ref.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }, 100);
  };

  return (
    <>
      <div>
        <Head>
          <title>BlockBenny</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="font-play min-h-screen bg-gradient-to-br from-bgTL via-bgVIA to-bgTL">
          <nav
            sticky="top"
            className="z-10 px-32 fixed min-w-full top-0 py-10 flex justify-between pr-48"
          >
            <div className="flex">
              <Image className="mr-10" src={logo} />
              <a
                onClick={() => {
                  nextSection2("home");
                }}
                className="text-white px-4 py-2 ml-8 text-xl"
                href="#"
              >
                <h1 className="self-center text-3xl text-white font-playB">
                  BlockBenny
                </h1>
              </a>
            </div>
            <ul className="flex items-center pr-10">
              <li>
                <a
                  onClick={() => {
                    nextSection2("home");
                  }}
                  className="text-white px-4 py-2 ml-8 text-xl"
                  href="#"
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  onClick={() => {
                    nextSection2("techstack");
                  }}
                  className="text-white px-4 py-2 ml-8 text-xl"
                  href="#"
                >
                  Tech Stack
                </a>
              </li>
              <li>
                <a
                  onClick={() => {
                    nextSection2("resume");
                  }}
                  className="text-white px-4 py-2 ml-8 text-xl"
                  href="#"
                >
                  Resume
                </a>
              </li>
              <li>
                <a
                  onClick={() => {
                    nextSection2("about");
                  }}
                  className="text-white px-4 py-2 ml-8 text-xl"
                  href="#"
                >
                  About Me
                </a>
              </li>
              <li>
                <CiTwitter className="h-10 w-10 ml-8" />
              </li>
              <li>
                <CiLinkedin className="h-10 w-10 ml-8" />
              </li>
              <li>
                <AiFillGithub className="h-10 w-10 ml-8" />
              </li>
            </ul>
          </nav>
          <Home />
          <TechStack />
          <Resume />
          <About />
        </main>
      </div>
    </>
  );
}
