import React, { Component, useRef, useEffect, useState } from "react";
import Head from "next/head";
import { CiTwitter, CiLinkedin } from "react-icons/ci";
import { AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import logo from "../public/BB.png";
import Home from "./home";
import Resume from "./resume";
import About from "./about";
import dynamic from "next/dynamic";
import { AiOutlineDownCircle } from "react-icons/ai";

export default function Index() {
  const TechStack = dynamic(() => import("./techstack"), { ssr: false });

  useEffect(() => {
    const onScroll = () => SetNextSection(window.pageYOffset);
    window.addEventListener("scroll", onScroll, { passive: true });
  }, []);

  var lastY = 0;
  const SetNextSection = (px) => {
    if (lastY > 900 && px < 900) {
      switchSection("navHome");
      changeNavigator("techstack", "Tech Stack", false);
    }
    if ((lastY < 900 && px > 900) || (lastY > 2000 && px < 2000)) {
      switchSection("navTech");
      changeNavigator("resume", "Resume", false);
    }
    if ((lastY < 2000 && px > 2000) || (lastY > 3500 && px < 3500)) {
      switchSection("navResume");
      changeNavigator("about", "About Me", false);
    }
    if (lastY < 3500 && px > 3500) {
      switchSection("navAbout");
      changeNavigator("", "", true);
    }
    lastY = px;
  };

  const switchSection = (current) => {
    clearNav();
    var ref = document.getElementById(current);
    ref.classList.add("text-textPink", "font-playB");
  };

  const changeNavigator = (next, title, hidden) => {
    var ref = document.getElementById("navigator");
    if (hidden) {
      ref.classList.add("hidden");
    } else {
      ref.classList.remove("hidden");
      nextNavSection = next;
      var refTitle = document.getElementById("navigatorTitle");
      refTitle.innerHTML = title;
    }
  };

  const clearNav = () => {
    var ref = document.getElementById("navHome");
    ref.classList.remove("text-textPink", "font-playB");
    var ref = document.getElementById("navTech");
    ref.classList.remove("text-textPink", "font-playB");
    var ref = document.getElementById("navResume");
    ref.classList.remove("text-textPink", "font-playB");
    var ref = document.getElementById("navAbout");
    ref.classList.remove("text-textPink", "font-playB");
  };

  var nextNavSection = "techstack";

  const scrollIntoSection = (sectionId) => {
    console.log("Scroll into section");
    console.log(sectionId);
    var el = document.getElementById(sectionId);
    console.log(el.offsetTop);
    window.scroll({ top: el.offsetTop, behavior: "smooth" });
  };

  return (
    <>
      <div>
        <Head>
          <title>BlockBenny</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="font-play min-h-screen bg-gradient-to-br from-bgTL via-bgVIA to-bgTL">
          <nav
            sticky="top"
            className="z-50 px-32 fixed min-w-full top-0 py-10 flex justify-between pr-48"
          >
            <div className="flex z-80 relative">
              <Image className="ml-32" src={logo} />
              <a
                onClick={() => {
                  scrollIntoSection("home");
                }}
                className="text-white px-4 py-2 ml-8 text-xl"
              >
                <h1 className="cursor-pointer  self-center text-3xl text-white font-playB">
                  BlockBenny
                </h1>
              </a>
            </div>
            <ul className="flex items-center pr-10">
              <li>
                <a
                  id="navHome"
                  onClick={() => {
                    scrollIntoSection("home");
                  }}
                  className="cursor-pointer text-textPink font-playB px-4 py-2 ml-8 text-xl"
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  id="navTech"
                  onClick={() => {
                    scrollIntoSection("techstack");
                  }}
                  className="cursor-pointer  px-4 py-2 ml-8 text-xl"
                >
                  Tech Stack
                </a>
              </li>
              <li>
                <a
                  id="navResume"
                  onClick={() => {
                    scrollIntoSection("resume");
                  }}
                  className=" cursor-pointer px-4 py-2 ml-8 text-xl"
                >
                  Resume
                </a>
              </li>
              <li>
                <a
                  id="navAbout"
                  onClick={() => {
                    scrollIntoSection("about");
                  }}
                  className="cursor-pointer  px-4 py-2 ml-8 text-xl"
                >
                  About Me
                </a>
              </li>
              <li>
                <CiTwitter
                  onClick={() =>
                    window.open("https://twitter.com/Wen_Alpha", "_blank")
                  }
                  className="cursor-pointer h-10 w-10 ml-8"
                />
              </li>
              <li>
                <CiLinkedin
                  onClick={() =>
                    window.open(
                      "https://www.linkedin.com/in/bennyblock/",
                      "_blank"
                    )
                  }
                  className="cursor-pointer h-10 w-10 ml-8"
                />
              </li>
              <li>
                <AiFillGithub
                  onClick={() =>
                    window.open("https://github.com/BlockBenny", "_blank")
                  }
                  className="cursor-pointer h-10 w-10 ml-8"
                />
              </li>
            </ul>
          </nav>
          <Home />
          <TechStack />
          <Resume />
          <About />
          <div
            id="navigator"
            className="w-full b-5 flex justify-center fixed bottom-0 z-80"
          >
            <div
              id="navigatorTitle"
              className="z-20 absolute bottom-24 text-xl"
            >
              Tech Stack
            </div>
            <AiOutlineDownCircle
              id="navigatorCircle"
              onClick={() => scrollIntoSection(nextNavSection)}
              className="z-20 cursor-pointer absolute bottom-12 h-10 w-10"
            />
          </div>
          <div className="area">
            <ul className="circles">
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
            </ul>
          </div>
        </main>
      </div>
    </>
  );
}
